#!/bin/sh

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1}'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:
if [ "$(hostname)" = "pad" ] || [ "$(hostname)" = "järkäle" ]; then
  exec conky -c $HOME/.conkyrc.laptop
else
  exec conky -c $HOME/.conkyrc
fi
echo $(hostname)
