#!/usr/bin/env bash
#

declare -A MYSNIPPETS
SNIPFILE="$HOME/scripts/snippets"
SEPARATORCHAR=': '

# loading snippets from file into array
while read line
do
  key=`echo $line | awk -F "$SEPARATORCHAR" '{print $1}'`
  value=`echo $line | awk -F "$SEPARATORCHAR" '{print $2}'`
  MYSNIPPETS["$key"]="$value"
done < $SNIPFILE

if [ -z "$@" ]
then
    echo -en "\x00prompt\x1fSnippet\n"
    echo -en "\0markup-rows\x1ftrue\n"
    echo -en "\0message\x1fSnippets starting by <i>cmd</i> are eval'd\n"

    for K in "${!MYSNIPPETS[@]}";
    do
        echo $K
    done
else
  snippet=$@
  if [ $snippet = "quit" ]
  then
      exit 0
  fi
  if [ ${MYSNIPPETS[$snippet]+_} ]
  then
    if [[ $snippet = cmd* ]]
    then
      x=`eval ${MYSNIPPETS[$snippet]}`
      coproc (echo -n "$x" | xdotool type --clearmodifiers --file -)
    else
      coproc (echo -n ${MYSNIPPETS[$snippet]} | xdotool type --clearmodifiers --file -)
    fi
  fi
fi
